- name: Playbook for globalvariable
  hosts: all
  vars:
        URL: "www.google.com"
  tasks:
        - name: Print msg of variable
          debug:
          msg: "Please visit this {{URL}}"

        - name: Print msg of variable
          debug:
          msg: "Please visit this {{URL}}"

